# Uncomment the next line to define a global platform for your project

platform :ios, '15.2'

target 'firestore' do

use_frameworks!


pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Firestore'
end
